version: "3"
services:
  app:
    build:
      context: .
    environment:
      - API_ID= 
      - API_HASH= 
      - BOT_TOKEN= 
      - LOG_CHANNEL= 
      - OWNER_ID=
    volumes:
      - ./downloads:/app/downloads
    restart: unless-stopped
